// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewApp.API.Models;

namespace NewApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191219105848_addnew")]
    partial class addnew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("NewApp.API.Models.Characteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Alcohol");

                    b.Property<int>("RestaurantId");

                    b.Property<string>("Seating");

                    b.Property<string>("Special_tags");

                    b.Property<string>("payment");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("NewApp.API.Models.Fooditem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsMain");

                    b.Property<string>("Name");

                    b.Property<int>("RestaurantId");

                    b.Property<string>("category");

                    b.Property<string>("imageurl");

                    b.Property<int>("price");

                    b.Property<string>("type");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("NewApp.API.Models.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<int>("Rating");

                    b.Property<string>("TimeInterval");

                    b.Property<string>("Timings");

                    b.Property<string>("Url");

                    b.Property<int>("contact_number");

                    b.Property<string>("contact_person");

                    b.Property<string>("type");

                    b.Property<string>("website");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("NewApp.API.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Breakfast");

                    b.Property<bool>("Cafe");

                    b.Property<int>("CharacteristicId");

                    b.Property<bool>("Dinner");

                    b.Property<bool>("Nightlife");

                    b.Property<bool>("lunch");

                    b.Property<string>("other");

                    b.HasKey("Id");

                    b.HasIndex("CharacteristicId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("NewApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewApp.API.Models.Characteristic", b =>
                {
                    b.HasOne("NewApp.API.Models.Restaurant", "Restaurant")
                        .WithMany("Characteristics")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewApp.API.Models.Fooditem", b =>
                {
                    b.HasOne("NewApp.API.Models.Restaurant", "Restaurant")
                        .WithMany("Fooditems")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NewApp.API.Models.Service", b =>
                {
                    b.HasOne("NewApp.API.Models.Characteristic", "Characteristic")
                        .WithMany("Services")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
